version: '3'

services:
  neo4j:
    image: 'neo4j:3.5.16'
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: 'neo4j/test'
    healthcheck:
      test: ["CMD", "wget", "--spider", "0.0.0.0:7474"]
      interval: 1m30s
      timeout: 10s
      retries: 5
